name: Publish Package to npmjs

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      # Setup .npmrc file to publish to npm
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          # Defaults to the user or organization that owns the workflow file
          scope: '@cell-x'
      
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install dependencies and Build package
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Publish Package to npmjs
        run: npm publish --access public
